apiVersion: v1
kind: Secret
metadata:
  name: vectora-secrets
  namespace: vectora
type: Opaque
stringData:
  MONGODB_URI: mongodb://vectora-mongodb:27017/vectora
  JWT_SECRET: change-me-jwt-secret
  GEMINI_API_KEY: change-me-gemini-api-key
